### PR TITLE
debt!: remove metabase visualisation link type

### PR DESCRIPTION
**Pull request by samuelhwilliams**
### Description of change
BREAKING CHANGE: Remove the 'Metabase' visualisation type.

### Checklist

* [x] Have tests been added to cover any changes?
* [x] Has the [CHANGELOG](https://github.com/uktrade/data-workspace/blob/master/CHANGELOG.md) been updated?
* [ ] Has the README been updated (if needed)?

### CODE REVIEW

**Review by michalc — APPROVED** [review]
Looks good

For the avoidance of doubt for posterity, I think this removes the 2 sorts of metabase we have: both the "tool" version where one instance is launched per user, and the multi-user version. The Dockerfile for the multi-user version is at https://github.com/uktrade/metabase, which I imagine should be archived.

**Comment by samuelhwilliams** [comment]
@michalc good call out. Are you OK planning the TF changes and making sure it's all OK (e.g. in dev) before we merge?

**Comment by michalc** [comment]
@samuelhwilliams Done both, and the TF seems all fine (and added the Data Workspace team to that repo, just for completeness)

**Comment by samuelhwilliams** [comment]
@michalc great - would you mind applying it to the rest of the envs when you have time then please? :)

**Pull request merged**
